export const data1 = [
  {
    id: 11,
    title: "Alata",
    price: 2513,
    originalPrice: 3513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-1-1.png",
  },
  {
    id: 12,
    title: "Alata",
    price: 1513,
    originalPrice: 2513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-1-2.png",
  },
  {
    id: 13,
    title: "Alata",
    price: 2513,
    originalPrice: 3513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-1-3.png",
  },
  {
    id: 14,
    title: "Alata",
    price: 6513,
    originalPrice: 7513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-1-4.png",
  },
  {
    id: 15,
    title: "Alata",
    price: 3513,
    originalPrice: 4513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-1-5.png",
  },
  {
    id: 16,
    title: "Alata",
    price: 8513,
    originalPrice: 9513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-1-6.png",
  },
  {
    id: 17,
    title: "Alata",
    price: 1513,
    originalPrice: 2213,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-1-7.png",
  },
  {
    id: 18,
    title: "Alata",
    price: 9513,
    originalPrice: 10513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-1-8.png",
  },
];

export const data2 = [
  {
    id: 21,
    title: "Alata",
    price: 2513,
    originalPrice: 3513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-2-1.png",
  },
  {
    id: 22,
    title: "Alata",
    price: 1213,
    originalPrice: 1513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-2-2.png",
  },
  {
    id: 23,
    title: "Alata",
    price: 5113,
    originalPrice: 6113,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-2-3.png",
  },
  {
    id: 24,
    title: "Alata",
    price: 4513,
    originalPrice: 5213,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-2-4.png",
  },
  {
    id: 25,
    title: "Alata",
    price: 1513,
    originalPrice: 2213,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-2-5.png",
  },
  {
    id: 26,
    title: "Alata",
    price: 4513,
    originalPrice: 5213,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-2-6.png",
  },
];

export const similar_products = [
  {
    id: "s1",
    title: "Alata",
    price: 2513,
    originalPrice: 3513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/s1.png",
  },
  {
    id: "s2",
    title: "Alata",
    price: 1513,
    originalPrice: 2213,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/s2.png",
  },
  {
    id: "s3",
    title: "Alata",
    price: 2513,
    originalPrice: 3513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/s3.png",
  },
  {
    id: "s4",
    title: "Alata",
    price: 6513,
    originalPrice: 7513,
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/s4.png",
  },
  {
    id: "s5",
    title: "Alata",
    price: 3513,
    originalPrice: 4513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s5.png",
  },
  {
    id: "s6",
    title: "Alata",
    price: 8513,
    originalPrice: 9513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s6.png",
  },
  {
    id: "s7",
    title: "Alata",
    price: 1513,
    originalPrice: 2213,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s7.png",
  },
  {
    id: "s8",
    title: "Alata",
    price: 9513,
    originalPrice: 10513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s8.png",
  },
  {
    id: "s9",
    title: "Alata",
    price: 9513,
    originalPrice: 10513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s9.png",
  },
  {
    id: "s10",
    title: "Alata",
    price: 9513,
    originalPrice: 10513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s10.png",
  },
  {
    id: "s11",
    title: "Alata",
    price: 9513,
    originalPrice: 10513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s11.png",
  },
  {
    id: "s12",
    title: "Alata",
    price: 9513,
    originalPrice: 10513,
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s12.png",
  },
];
