export const data1 = [
  {
    id: 11,
    title: "Alata",
    price: "2,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-1-1.png",
    discount: 30,
  },
  {
    id: 12,
    title: "Alata",
    price: "1,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-1-2.png",
    discount: 30,
  },
  {
    id: 13,
    title: "Alata",
    price: "2,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-1-3.png",
    discount: 30,
  },
  {
    id: 14,
    title: "Alata",
    price: "6,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-1-4.png",
    discount: 30,
  },
  {
    id: 15,
    title: "Alata",
    price: "3,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-1-5.png",
    discount: 30,
  },
  {
    id: 16,
    title: "Alata",
    price: "8,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-1-6.png",
    discount: 30,
  },
  {
    id: 17,
    title: "Alata",
    price: "1,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-1-7.png",
    discount: 30,
  },
  {
    id: 18,
    title: "Alata",
    price: "9,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-1-8.png",
    discount: 30,
  },
];

export const data2 = [
  {
    id: 21,
    title: "Alata",
    price: "2,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-2-1.png",
    discount: 30,
  },
  {
    id: 22,
    title: "Alata",
    price: "1,213",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-2-2.png",
    discount: 30,
  },
  {
    id: 23,
    title: "Alata",
    price: "5,113",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-2-3.png",
    discount: 30,
  },
  {
    id: 24,
    title: "Alata",
    price: "4,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/p-2-4.png",
    discount: 30,
  },
  {
    id: 25,
    title: "Alata",
    price: "1,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-2-5.png",
    discount: 30,
  },
  {
    id: 26,
    title: "Alata",
    price: "4,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/p-2-6.png",
    discount: 30,
  },
];

export const similar_products = [
  {
    id: "s1",
    title: "Alata",
    price: "2,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/s1.png",
    discount: 30,
  },
  {
    id: "s2",
    title: "Alata",
    price: "1,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/s2.png",
    discount: 30,
  },
  {
    id: "s3",
    title: "Alata",
    price: "2,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/s3.png",
    discount: 30,
  },
  {
    id: "s4",
    title: "Alata",
    price: "6,513",
    description: "Women cotton printed long dress gown",
    category: "men clothing",
    image: "/assets/images/s4.png",
    discount: 30,
  },
  {
    id: "s5",
    title: "Alata",
    price: "3,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s5.png",
    discount: 30,
  },
  {
    id: "s6",
    title: "Alata",
    price: "8,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s6.png",
    discount: 30,
  },
  {
    id: "s7",
    title: "Alata",
    price: "1,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s7.png",
    discount: 30,
  },
  {
    id: "s8",
    title: "Alata",
    price: "9,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s8.png",
    discount: 30,
  },
  {
    id: "s9",
    title: "Alata",
    price: "9,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s9.png",
    discount: 30,
  },
  {
    id: "s10",
    title: "Alata",
    price: "9,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s10.png",
    discount: 30,
  },
  {
    id: "s11",
    title: "Alata",
    price: "9,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s11.png",
    discount: 30,
  },
  {
    id: "s12",
    title: "Alata",
    price: "9,513",
    description: "Women cotton printed long dress gown",
    category: "jewelery",
    image: "/assets/images/s12.png",
    discount: 30,
  },
];